fittings/urls.py
from django.urls import re_path

from . import views

app_name = 'fittings'

urlpatterns = [
    re_path(r'^$', views.dashboard, name='dashboard'),
    re_path(r'^fit/add/$', views.add_fit, name='add_fit'),
    re_path(r'^fit/all/$', views.view_all_fits, name='view_all_fits'),
    re_path(r'^fit/(?P<fit_id>[0-9]+)/$', views.view_fit, name='view_fit'),
    re_path(r'^fit/(?P<fit_id>[0-9]+)/delete/$', views.delete_fit, name='delete_fit'),
    re_path(r'^fit/(?P<fit_id>[0-9]+)/save/$', views.save_fit, name='save_fit'),
    re_path(r'^fit/(?P<fit_id>[0-9]+)/edit/$', views.edit_fit, name='edit_fit'),
    re_path(r'^doctrine/add/$', views.add_doctrine, name='add_doctrine'),
    re_path(r'^doctrine/(?P<doctrine_id>[0-9]+)/$', views.view_doctrine, name='view_doctrine'),
    re_path(r'^doctrine/(?P<doctrine_id>[0-9]+)/delete/$', views.delete_doctrine, name='delete_doctrine'),
    re_path(r'^doctrine/(?P<doctrine_id>[0-9]+)/edit/$', views.edit_doctrine, name='edit_doctrine'),
    re_path(r'^cat/all/$', views.view_all_categories, name='view_all_categories'),
    re_path(r'^cat/add/$', views.add_category, name='add_category'),
    re_path(r'^cat/(?P<cat_id>[0-9]+)/$', views.view_category, name='view_category'),
    re_path(r'^cat/(?P<cat_id>[0-9]+)/edit/$', views.edit_category, name='edit_category'),
    re_path(r'^cat/(?P<cat_id>[0-9]+)/delete/$', views.delete_category, name='delete_category'),
]

fittings/templates/fittings/add_fit.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% block page_title %}{% translate "Add Fit" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                {% translate "Add Fitting" %}
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="description" class="col-sm-2 control-label">{% translate "Description" %}</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" name="description" id="description" maxlength="500" rows="3"></textarea>
                                </div>
                            </div>
                            <br>
                            <div class="form-group" >
                                <label for="eft" class="col-sm-2 control-label">{% translate "Fit" %}</label>
                                <div class="col-sm-10" style="margin-top: 5px; margin-bottom: 5px;">
                                    <textarea class="form-control" name="eft" id="eft" rows="50"></textarea>
                                </div>
                            </div>
                            <br>
                            <button class="btn btn-primary btn-block" type="submit">{% translate "Submit" %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

fittings/templates/fittings/dashboard.html
{% extends 'fittings/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load evelinks %}
{% load tags %}

{% block page_title %}{% translate "Dashboard" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
        <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times</span>
            </button>
            <h4>
                {% if msg.0 == 'danger' %}
                    {% translate "Oh No!" %}
                {% elif msg.0 == 'success' %}
                    {% translate "Success!" %}
                {% endif %}
            </h4>
            <p>{{ msg.1 }}</p>
        </div>
    {% endif %}
    <div class="container col-sm-12">
        <h2>
            {% translate "Doctrine List" %}
        </h2>
        <div class="panel panel-default">
            <div class="panel-heading">
                {% translate "Doctrines" %}
            </div>
            <div class="panel-body">
                {% if not docs %}
                    <div class="alert alert-warning text-center">{% translate "No Doctrines Found" %} </div>
                {% else %}
                    <table class="table table-hover dataTable" id="docTable">
                        <thead>
                            <tr>
                                <th> </th>
                                <th>{% translate "Name" %}</th>
                                <th>{% translate "Categories" %}</th>
                                <th>{% translate "Description" %}</th>
                                <th>{% translate "Ships" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for doc in docs %}
                                <tr>
                                    <td> <a href="{% url 'fittings:view_doctrine' doc.pk %}"><img src="{{ doc.icon_url }}" class="img-circle" style="display: block; margin: auto;"> </a></td>
                                    <td> <a href="{% url 'fittings:view_doctrine' doc.pk %}">{{ doc.name }}</a> </td>
                                    <td>
                                        {% for cat in doc.category.all %}
                                            <span class="label" style="background-color: {{cat.color}};"><a href="{% url 'fittings:view_category' cat.pk %}" class="nostyle">{{cat.name}}</a></span>
                                        {% endfor %}
                                    </td>
                                    <td> {{ doc.description|linebreaks }} </td>
                                    <td>
                                        {% for fitting in doc_dict|get_item:doc.pk %}
                                            <img src="{{ fitting.ship_type_type_id|type_render_url:32 }}" class="img-circle" data-toggle="tooltip" data-placement="bottom" title="{{ fitting.ship_type.name }}">
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    {% get_dt_lang LANGUAGE_CODE as LANG_PATH %}
    $(document).ready(function(){
        $('#docTable').DataTable({
            language: { url: '{% static LANG_PATH %}' },
            "order": [[ 1, "asc" ]],
        });
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}

fittings/templates/fittings/view_all_categories.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load static %}
{% load tags %}


{% block page_title %}{% translate "View All Categories" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times</span>
                </button>
                <h4>
                    {% if msg.0 == 'danger' %}
                        {% translate "Oh No!" %}
                    {% elif msg.0 == 'success' %}
                        {% translate "Success!" %}
                    {% endif %}
                </h4>
                <p>{{ msg.1 }}</p>
            </div>
    {% endif %}
    <div class="container col-sm-12">
        <h2>
            {% translate "Category List" %}
        </h2>
        <div class="panel panel-default">
            <div class="panel-heading">
                {% translate "Fits" %}
            </div>
            <div class="panel-body">
                {% if not cats %}
                    <div class="alert alert-warning text-center">{% translate "No Categories Found" %}</div>
                {% else %}
                    <table class="table table-hover dataTable" id="fitTable">
                        <thead>
                            <tr>
                                <th>{% translate "Name" %}</th>
                                <th>{% translate "Doctrines Assigned" %}</th>
                                <th>{% translate "Fittings Assigned" %}</th>
                                {% if perms.fittings.manage %}
                                    <th>{% translate "Groups Assigned" %}</th>
                                    <th> </th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for cat in cats %}
                                <tr>
                                    <td> <span class="label" style="background-color: {{cat.color}};"><a href="{% url 'fittings:view_category' cat.pk %}" class="nostyle">{{cat.name}}</a></span> </td>
                                    <td> {{ cat.doctrines_count }}</td>
                                    <td> {{ cat.total_fits }} </td>
                                    {% if perms.fittings.manage %}
                                        <td> {{ cat.groups_count }}</td>
                                        <td>
                                            <a href="{% url 'fittings:view_category' cat.pk %}" type="button" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="{% translate 'View Category' %}">
                                                <span class="fa fas fa-eye"></span>
                                            </a>
                                            <a href="{% url 'fittings:edit_category' cat.pk %}" type="button" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="{% translate 'Edit Category' %}">
                                                <span class="fa fas fa-pencil-alt"></span>
                                            </a>
                                            <a href="{% url 'fittings:delete_category' cat.pk %}" type="button" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="{% translate 'Delete Category' %}">
                                                <span class="fa fas fa-times"></span>
                                            </a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <h6><i><i class="fas fa-exclamation-triangle"></i>{% translate "*Note: Fit counts may be inaccurate as fits marked independently of doctrines may be counted more than once." %}</i></h6>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    {% get_dt_lang LANGUAGE_CODE as LANG_PATH %}
    $(document).ready(function(){
        $('#fitTable').DataTable({
            language: { url: '{% static LANG_PATH %}' },
        });
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}

fittings/templates/fittings/view_all_fits.html
{% extends 'fittings/base.html' %}
{% load tags %}
{% load static %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load evelinks %}

{% block page_title %}{% translate "View All Fits" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}
                        <h4>
                            {% if msg.0 == 'danger' %}
                                {% translate "Oh No!" %}
                            {% elif msg.0 == 'success' %}
                                {% translate "Success!" %}
                            {% endif %}
                        </h4>
                    {% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <h2>
            {% translate "Fit List" %}
        </h2>
        <div class="panel panel-default">
            <div class="panel-heading">
                {% translate "Fits" %}
            </div>
            <div class="panel-body">
                {% if not fits %}
                    <div class="alert alert-warning text-center">{% translate "No Fits Found" %}</div>
                {% else %}
                    <table class="table table-hover dataTable" id="fitTable">
                        <thead>
                            <tr>
                                <th>{% translate "Name" %}</th>
                                <th>{% translate "Categories" %}</th>
                                <th>{% translate "Description" %}</th>
                                <th>{% translate "Ship Type" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for fit in fits %}
                                <tr>
                                    <td> <a href="{% url 'fittings:view_fit' fit.pk %}">{{ fit.name }}</a> </td>
                                    <td>
                                        {% for cat in cats|get_item:fit.pk %}
                                        <span class="label" style="background-color: {{cat.color}};"><a href="{% url 'fittings:view_category' cat.pk %}" class="nostyle">{{cat.name}}</a></span>
                                        {% endfor %}
                                    </td>
                                    <td> {{ fit.description }} </td>
                                    <td> <img class="img-circle" src="{{ fit.ship_type_type_id|type_render_url:32 }}" title="{{ fit.ship_type.name }}"> {{ fit.ship_type.name }} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    {% get_dt_lang LANGUAGE_CODE as LANG_PATH %}
    $(document).ready(function(){
        $('#fitTable').DataTable({
            language: { url: '{% static LANG_PATH %}' },
        });
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}

fittings/templates/fittings/view_category.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load static %}
{% load evelinks %}

{% block more_css %}
    <style>
        .tp {
            padding-bottom: 0;
        }
        .btm {
            padding-top: 5px;
            padding-left: 0;
            padding-right: 0;
        }
        .pd {
            padding-left: 15px;
            padding-right: 15px;
        }
        .mv {
            margin-left: 15px;
        }
    </style>
    {% include 'bundles/datatables-css.html' %}
{% endblock %}

{% block page_title %}{% translate "View Category" %}{% endblock %}

{% block fittings_block %}
    <div class="container col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                {% translate "Category" %}
                {% if perms.fittings.manage %}
                <div class="pull-right" style="margin-top: -2px !important;">
                   <a href="{% url 'fittings:edit_category' cat.pk %}" type="button" class="btn btn-xs btn-warning" data-toggle="tooltip" data-placement="top" title="{% translate 'Edit Category' %}">
                       <span class="fa fas fa-pencil-alt"></span>
                   </a>
                    <a href="{% url 'fittings:delete_category' cat.pk %}" type="button" class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="{% translate 'Delete Category' %}">
                        <span class="fa fas fa-times"></span>
                    </a>
                </div>
                {% endif %}
            </div>
            <div class="panel-body tp">
                <strong>{% translate "Name" %}: </strong>
                <br>
                <span class="label" style="background-color: {{cat.color}};">{{cat.name}}</span>
                <div id="spacer" style="padding-top: 5px;"></div>
                {% if perms.fittings.manage %}
                    <strong>{% translate "Groups" %}: </strong>
                    <br>
                    {% if cat.groups.all|length != 0 %}
                      {% for group in cat.groups.all %} <span class="label label-primary">{{group.name}}</span> {% endfor %}
                    {% else %}
                      <span class="label label-warning">{% translate "Category is public" %}</span>
                    {% endif %}
                {% endif %}

            </div>
            <div class="panel-body btm">
                <ul class="nav nav-tabs" style="margin-bottom: 10px;">
                    <li class="active mv"><a data-toggle="tab" href="#doctrines">{% translate "Doctrines" %}</a></li>
                    <li><a data-toggle="tab" href="#fittings">{% translate "Fittings" %}</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade-in active panel-default pd" id="doctrines">
                        <table class="table table-striped dataTable" role="table" id="docTable">
                            <thead>
                                <tr>
                                    <th> </th>
                                    <th>{% translate "Name" %}</th>
                                    <th>{% translate "Categories" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th>{% translate "Ships" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if not docs %}
                                    <tr>
                                        <td colspan="5">
                                            <div class="alert alert-warning text-center"> {% translate "No Doctrines Found" %} </div>
                                        </td>
                                    </tr>
                                {% else %}
                                    {% for doc in docs %}
                                        <tr>
                                            <td> <a href="{% url 'fittings:view_doctrine' doc.pk %}"><img src="{{ doc.icon_url }}" class="img-circle" style="display: block; margin: auto;"> </a></td>
                                            <td> <a href="{% url 'fittings:view_doctrine' doc.pk %}">{{ doc.name }}</a> </td>
                                            <td>
                                                {% for cate in doc.category.all %}
                                                <span class="label" style="background-color: {{cate.color}};"><a href="{% url 'fittings:view_category' cate.pk %}" class="nostyle">{{cate.name}}</a></span>
                                                {% endfor %}
                                            </td>
                                            <td> {{ doc.description }} </td>
                                            <td>
                                                {% for fitting in doc_dict|get_item:doc.pk %}
                                                    <img src="{{ fitting.ship_type_type_id|type_render_url:32 }}" class="img-circle" data-toggle="tooltip" data-placement="bottom" title="{{ fitting.ship_type.name }}">
                                                {% endfor %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade-in panel-default pd" id="fittings">
                        <table class="table table-hover dataTable" id="fitTable">
                            <thead>
                                <tr>
                                    <th>{% translate "Name" %}</th>
                                    <th>{% translate "Categories" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th>{% translate "Ship Type" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if not fits %}
                                    <tr>
                                        <td colspan="4">
                                            <div class="alert alert-warning text-center"> {% translate "No Fits Found" %} </div>
                                        </td>
                                    </tr>
                                {% else %}
                                    {% for fit in fits %}
                                        <tr>
                                            <td> <a href="{% url 'fittings:view_fit' fit.pk %}">{{ fit.name }}</a> </td>
                                            <td>
                                                {% for cate in cats|get_item:fit.pk %}
                                                <span class="label" style="background-color: {{cate.color}};"><a href="{% url 'fittings:view_category' cate.pk %}" class="nostyle">{{cate.name}}</a></span>
                                                {% endfor %}
                                            </td>
                                            <td> {{ fit.description }} </td>
                                            <td> <img class="img-circle" src="{{ fit.ship_type_type_id|type_render_url:128 }}" style="height: 32px; width: 32px;" title="{{ fit.ship_type.name }}"> {{ fit.ship_type.name }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    $(document).ready(function(){
        $('#docTable').DataTable({
            "order": [[ 1, "asc" ]],
        });
        $('[data-toggle="tooltip"]').tooltip();
        $('#fitTable').DataTable();
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}

fittings/templates/fittings/view_doctrine.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load static %}
{% load evelinks %}
{% load tags %}

{% block page_title %}{{ doctrine.name }} {% translate "Doctrine" %}{% endblock %}

{% block fittings_block %}
    {# modal start #}
    <div class="modal fade" id="deleteModal" role="dialog" tabindex="-1" aria-labelledby="modalTitle">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modalTitle">{% translate "Are you sure?" %}</h4>
                </div>
                <div class="modal-body">
                    <p style="white-space: pre-line;">
                        {% translate "Are you sure you wish to delete this doctrine?" %}
                        <i><strong>{% translate "This action is permanent." %}</strong></i>
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% translate "No - Close" %}</button>
                    <a href="{% url 'fittings:delete_doctrine' doctrine.pk %}" type="button" class="btn btn-danger">{% translate "Yes - Delete" %}</a>
                </div>
            </div>
        </div>
    </div>

    {# modal end #}
    <br>
    <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                {% translate "Doctrine Information" %}

                {% if perms.fittings.manage %}
                    <span data-toggle="modal" data-target="#deleteModal">
                        <button class="btn btn-xs btn-danger" style="float: right; margin-left: 5px;" data-toggle="tooltip" data-placement="top" title="{% translate 'Delete Doctrine' %}"><span class="fa fas fa-times"></span> </button>
                    </span>
                    <a href="{% url 'fittings:edit_doctrine' doctrine.pk %}" class="btn btn-xs btn-warning" style="float: right;" data-toggle="tooltip" data-placement="top" title="{% translate 'Edit Doctrine' %}"><span class="fa fas fa-pencil-alt"></span> </a>
                {% endif %}
            </div>
            <div class="panel-body">
                <img src="{{ doctrine.icon_url }}" class="img-circle center-block text-center">
                <h4 class="text-center">{{ doctrine.name }}</h4>
                <h5 class="text-center">
                        {% for cat in d_cats %}
                            <span class="label" style="background-color: {{cat.color}};"><a href="{% url 'fittings:view_category' cat.pk %}" class="nostyle">{{cat.name}}</a></span>
                        {% endfor %}
                </h5>
                <hr>
                <dl>
                    <dt>{% translate "Description" %}</dt>
                    <dd><pre>{{ doctrine.description|break_html_lines|striptags }}</pre></dd>
                    {% if doctrine.created %}
                    <dt>{% translate "Created" %}</dt>
                        {% if LANGUAGE_CODE == 'ko' or LANGUAGE_CODE == 'ja' %}
                            <dd>{{ doctrine.created|date:'Y-m-d / H:i:s' }}</dd>
                        {% else %}
                            <dd>{{ doctrine.created|date:'d M Y H:i:s' }}</dd>
                        {% endif %}
                    {% endif %}
                    {% if doctrine.last_updated %}
                        <dt>{% translate "Last Updated" %}</dt>
                        {% if LANGUAGE_CODE == 'ko' or LANGUAGE_CODE == 'ja' %}
                            <dd>{{ doctrine.last_updated|date:'Y-m-d / H:i:s' }}</dd>
                        {% else %}
                            <dd>{{ doctrine.last_updated|date:'d M Y H:i:s' }}</dd>
                        {% endif %}
                    {% endif %}
                </dl>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">{% translate "Doctrine Fits" %}</div>
            <div class="panel-body">
                {% if not fits %}
                    <div class="alert alert-warning text-center">{% translate "No Fits Found" %}</div>
                {% else %}
                    <table class="table table-hover dataTable" id="fitsTable">
                        <thead>
                            <tr>
                                <th>{% translate "Name" %}</th>
                                <th>{% translate "Category" %}</th>
                                <th>{% translate "Description" %}</th>
                                <th>{% translate "Ship Type" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                                {% for fit in fits %}
                                    <tr>
                                        <td> <a href="{% url 'fittings:view_fit' fit.pk %}">{{ fit.name }}</a> </td>
                                        <td>
                                            {% for cat in f_cats|get_item:fit.pk %}
                                            <span class="label" style="background-color: {{cat.color}};"><a href="{% url 'fittings:view_category' cat.pk %}" class="nostyle">{{cat.name}}</a></span>
                                            {% endfor %}
                                        </td>
                                        <td> {{ fit.description }} </td>
                                        <td> <img class="img-circle" src="{{ fit.ship_type_type_id|type_render_url:32 }}" title="{{ fit.ship_type.name }}"> {{ fit.ship_type.name }}</td>
                                    </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    {% get_dt_lang LANGUAGE_CODE as LANG_PATH %}
     $(document).ready(function(){
        $('#fitsTable').DataTable({
            language: { url: '{% static LANG_PATH %}' },
            paging: false,
            searching: false,
            order: [[1, 'asc']],
        });
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}